/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as ApiTestMcpRouteImport } from './routes/api.test-mcp'
import { Route as ApiTestLlmRouteImport } from './routes/api.test-llm'
import { Route as ApiRealtimeRouteImport } from './routes/api.realtime'
import { Route as ApiDbRouteImport } from './routes/api.db'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestMcpRoute = ApiTestMcpRouteImport.update({
  id: '/api/test-mcp',
  path: '/api/test-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestLlmRoute = ApiTestLlmRouteImport.update({
  id: '/api/test-llm',
  path: '/api/test-llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbRoute = ApiDbRouteImport.update({
  id: '/api/db',
  path: '/api/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/db': typeof ApiDbRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/test-llm': typeof ApiTestLlmRoute
  '/api/test-mcp': typeof ApiTestMcpRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/db': typeof ApiDbRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/test-llm': typeof ApiTestLlmRoute
  '/api/test-mcp': typeof ApiTestMcpRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/db': typeof ApiDbRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/test-llm': typeof ApiTestLlmRoute
  '/api/test-mcp': typeof ApiTestMcpRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/db'
    | '/api/realtime'
    | '/api/test-llm'
    | '/api/test-mcp'
    | '/c/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/db'
    | '/api/realtime'
    | '/api/test-llm'
    | '/api/test-mcp'
    | '/c/$id'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/db'
    | '/api/realtime'
    | '/api/test-llm'
    | '/api/test-mcp'
    | '/c/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDbRoute: typeof ApiDbRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiTestLlmRoute: typeof ApiTestLlmRoute
  ApiTestMcpRoute: typeof ApiTestMcpRoute
  CIdRoute: typeof CIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-mcp': {
      id: '/api/test-mcp'
      path: '/api/test-mcp'
      fullPath: '/api/test-mcp'
      preLoaderRoute: typeof ApiTestMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-llm': {
      id: '/api/test-llm'
      path: '/api/test-llm'
      fullPath: '/api/test-llm'
      preLoaderRoute: typeof ApiTestLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db': {
      id: '/api/db'
      path: '/api/db'
      fullPath: '/api/db'
      preLoaderRoute: typeof ApiDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDbRoute: ApiDbRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiTestLlmRoute: ApiTestLlmRoute,
  ApiTestMcpRoute: ApiTestMcpRoute,
  CIdRoute: CIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
