/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as ApiTestMcpRouteImport } from './routes/api.test-mcp'
import { Route as ApiTestLlmRouteImport } from './routes/api.test-llm'
import { Route as ApiRealtimeRouteImport } from './routes/api.realtime'
import { Route as ApiDbRouteImport } from './routes/api.db'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiMcpCountRouteImport } from './routes/api.mcp.count'
import { Route as ApiConversationsEnsureRouteImport } from './routes/api.conversations.ensure'
import { Route as ApiAuthProfileRouteImport } from './routes/api.auth.profile'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiAdminUserAccessRouteImport } from './routes/api.admin.user-access'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestMcpRoute = ApiTestMcpRouteImport.update({
  id: '/api/test-mcp',
  path: '/api/test-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestLlmRoute = ApiTestLlmRouteImport.update({
  id: '/api/test-llm',
  path: '/api/test-llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbRoute = ApiDbRouteImport.update({
  id: '/api/db',
  path: '/api/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpCountRoute = ApiMcpCountRouteImport.update({
  id: '/api/mcp/count',
  path: '/api/mcp/count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsEnsureRoute = ApiConversationsEnsureRouteImport.update({
  id: '/api/conversations/ensure',
  path: '/api/conversations/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUserAccessRoute = ApiAdminUserAccessRouteImport.update({
  id: '/api/admin/user-access',
  path: '/api/admin/user-access',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/db': typeof ApiDbRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/test-llm': typeof ApiTestLlmRoute
  '/api/test-mcp': typeof ApiTestMcpRoute
  '/c/$id': typeof CIdRoute
  '/api/admin/user-access': typeof ApiAdminUserAccessRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/conversations/ensure': typeof ApiConversationsEnsureRoute
  '/api/mcp/count': typeof ApiMcpCountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/db': typeof ApiDbRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/test-llm': typeof ApiTestLlmRoute
  '/api/test-mcp': typeof ApiTestMcpRoute
  '/c/$id': typeof CIdRoute
  '/api/admin/user-access': typeof ApiAdminUserAccessRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/conversations/ensure': typeof ApiConversationsEnsureRoute
  '/api/mcp/count': typeof ApiMcpCountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/db': typeof ApiDbRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/test-llm': typeof ApiTestLlmRoute
  '/api/test-mcp': typeof ApiTestMcpRoute
  '/c/$id': typeof CIdRoute
  '/api/admin/user-access': typeof ApiAdminUserAccessRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/conversations/ensure': typeof ApiConversationsEnsureRoute
  '/api/mcp/count': typeof ApiMcpCountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/db'
    | '/api/realtime'
    | '/api/test-llm'
    | '/api/test-mcp'
    | '/c/$id'
    | '/api/admin/user-access'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/conversations/ensure'
    | '/api/mcp/count'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/db'
    | '/api/realtime'
    | '/api/test-llm'
    | '/api/test-mcp'
    | '/c/$id'
    | '/api/admin/user-access'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/conversations/ensure'
    | '/api/mcp/count'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/db'
    | '/api/realtime'
    | '/api/test-llm'
    | '/api/test-mcp'
    | '/c/$id'
    | '/api/admin/user-access'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/conversations/ensure'
    | '/api/mcp/count'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDbRoute: typeof ApiDbRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiTestLlmRoute: typeof ApiTestLlmRoute
  ApiTestMcpRoute: typeof ApiTestMcpRoute
  CIdRoute: typeof CIdRoute
  ApiAdminUserAccessRoute: typeof ApiAdminUserAccessRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiConversationsEnsureRoute: typeof ApiConversationsEnsureRoute
  ApiMcpCountRoute: typeof ApiMcpCountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-mcp': {
      id: '/api/test-mcp'
      path: '/api/test-mcp'
      fullPath: '/api/test-mcp'
      preLoaderRoute: typeof ApiTestMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-llm': {
      id: '/api/test-llm'
      path: '/api/test-llm'
      fullPath: '/api/test-llm'
      preLoaderRoute: typeof ApiTestLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db': {
      id: '/api/db'
      path: '/api/db'
      fullPath: '/api/db'
      preLoaderRoute: typeof ApiDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/count': {
      id: '/api/mcp/count'
      path: '/api/mcp/count'
      fullPath: '/api/mcp/count'
      preLoaderRoute: typeof ApiMcpCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/ensure': {
      id: '/api/conversations/ensure'
      path: '/api/conversations/ensure'
      fullPath: '/api/conversations/ensure'
      preLoaderRoute: typeof ApiConversationsEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user-access': {
      id: '/api/admin/user-access'
      path: '/api/admin/user-access'
      fullPath: '/api/admin/user-access'
      preLoaderRoute: typeof ApiAdminUserAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDbRoute: ApiDbRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiTestLlmRoute: ApiTestLlmRoute,
  ApiTestMcpRoute: ApiTestMcpRoute,
  CIdRoute: CIdRoute,
  ApiAdminUserAccessRoute: ApiAdminUserAccessRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiConversationsEnsureRoute: ApiConversationsEnsureRoute,
  ApiMcpCountRoute: ApiMcpCountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
